Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "host" do |host|
    host.vm.hostname = "host"
    host.vm.network "private_network", ip: "192.168.33.10"

    host.vm.provider "virtualbox" do |vb|
      vb.name = "host-jenkins-node"
      vb.gui = true
      vb.memory = 1024
      vb.cpus = 2
    end

    host.vm.provision "shell", path: "scripts/provision-jenkins.sh"
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.33.20"

    prod.vm.provider "virtualbox" do |vb|
      vb.name = "prod-node"
      vb.memory = "1024"
      vb.cpus = 1
    end

    prod.vm.provision "shell", path: "scripts/setup-node.sh"
  end

end
