Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.33.10"

    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
      vb.memory = 1024
      vb.cpus = 1
    end

    jenkins.vm.provision "shell", path: "scripts/setup-jenkins.sh"
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.33.20"

    prod.vm.provider "virtualbox" do |vb|
      vb.name = "prod-node"
      vb.memory = "1024"
      vb.cpus = 1
    end

    prod.vm.provision "shell", path: "scripts/setup-node.sh"
  end

end
